#!/usr/bin/env python3
"""run-vamp.py [HOST] -- the phase-0 spike on a real Amiga through amiagent.

Pushes spike.lisp, sendkey and a DOS run script into <OUT> on the box,
launches the script detached, waits for its done sentinel and prints the
run log.  The clamiga used is the installed release (RELEASE below).
Environment: AMIGA_HOST (default 192.168.50.235), AMIGA_TOKEN (required,
no default -- must match the agent server's token on the box),
SPIKE_RELEASE (the release drawer), SPIKE_OUT (scratch drawer)."""
import os, sys, time, subprocess
sys.path.insert(0, os.path.expanduser("~/Development/MySources/amimcp/server"))
from amiga import Amiga

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(HERE)
HOST = sys.argv[1] if len(sys.argv) > 1 else os.environ.get("AMIGA_HOST", "192.168.50.235")
TOKEN = os.environ["AMIGA_TOKEN"]
RELEASE = os.environ.get("SPIKE_RELEASE", "Work:Download/clamiga-0.10.0-snapshot-814c7017")
OUT = os.environ.get("SPIKE_OUT", "Work:Download/spike")
CLAMIGA = RELEASE + "/bin/aos3/clamiga"
STACK = os.environ.get("SPIKE_STACK", "128000")
EXTRA = os.environ.get("SPIKE_CLAMIGA_ARGS", "")   # e.g. --no-jit
TAG = os.environ.get("SPIKE_TAG", "vamp")

a = Amiga(HOST, token=TOKEN, timeout=600)

def sh(cmd, timeout=120):
    r = a.exec_command(cmd, timeout=timeout)
    return r if isinstance(r, str) else "\n".join(str(x) for x in r)

typing = subprocess.check_output(["sh", os.path.join(HERE, "typing.sh"), OUT + "/sendkey"]).decode()

script = f"""; spike run script, generated by spike/run-vamp.py
failat 21
cd {OUT}
Delete >NIL: spike-done spike-ready spike.log spike-buffer.txt spike-clamiga.log
echo "=== run start ===" >spike-run.log
version >>spike-run.log
echo "=== avail before ===" >>spike-run.log
avail >>spike-run.log
stack {STACK}
setenv CLAMIGA_MEM_DIAG 1
run >{OUT}/spike-clamiga.log {CLAMIGA} --no-userinit --heap 8M --non-interactive {EXTRA} --load {OUT}/spike-out.lisp --load {OUT}/spike.lisp
set n 0
LAB waitready
IF NOT EXISTS {OUT}/spike-ready
  IF $n EQ 120
    echo "FAIL the spike never opened its window" >>spike-run.log
    SKIP collect
  ENDIF
  set n `eval $n + 1`
  C:Wait 2
  SKIP waitready BACK
ENDIF
echo "OK spike window open after about $n x 2 s" >>spike-run.log
C:Wait 2
echo "=== avail with the spike running (before typing) ===" >>spike-run.log
avail >>spike-run.log
echo "=== typing ===" >>spike-run.log
date >>spike-run.log
{typing}
date >>spike-run.log
echo "=== avail with the spike running (after typing) ===" >>spike-run.log
avail >>spike-run.log
{OUT}/sendkey C-x C-c
set n 0
LAB waitreport
Search >NIL: QUIET spike.log "end report"
IF WARN
  IF $n EQ 300
    echo "FAIL the spike did not finish its report in time" >>spike-run.log
    SKIP collect
  ENDIF
  set n `eval $n + 1`
  C:Wait 2
  SKIP waitreport BACK
ENDIF
echo "OK spike finished about $n x 2 s after C-x C-c" >>spike-run.log
LAB collect
echo "=== spike.log ===" >>spike-run.log
IF EXISTS spike.log
  type spike.log >>spike-run.log
ENDIF
echo "=== spike-clamiga.log ===" >>spike-run.log
IF EXISTS spike-clamiga.log
  type spike-clamiga.log >>spike-run.log
ENDIF
echo "=== spike-buffer.txt ===" >>spike-run.log
IF EXISTS spike-buffer.txt
  type spike-buffer.txt >>spike-run.log
ENDIF
echo "=== avail after ===" >>spike-run.log
avail >>spike-run.log
echo "=== run end ===" >>spike-run.log
echo done >spike-done
"""

print("box:", a.system_info())
sh(f"MakeDir >NIL: {OUT}")
a.write_file(OUT + "/spike.lisp", open(os.path.join(HERE, "spike.lisp"), "rb").read())
a.write_file(OUT + "/sendkey", open(os.path.join(ROOT, "build", "cross", "sendkey"), "rb").read())
# AmigaDOS makes `*' an escape character inside quotes, so the form that
# names the output drawer cannot go on the command line: a preamble file.
a.write_file(OUT + "/spike-out.lisp", f'(defvar cl-user::*spike-out* "{OUT}/")\n'.encode("latin-1"))
a.write_file(OUT + "/run-spike", script.encode("latin-1"))
sh(f"Protect {OUT}/sendkey +e")
sh(f"Protect {OUT}/run-spike +s")
sh(f"Delete >NIL: {OUT}/spike-done")
# detached, so the agent's command slot stays free for polling
a.arexx(f"address command 'Run >NIL: Execute {OUT}/run-spike'")
print("launched; polling for", OUT + "/spike-done")
deadline = time.time() + 900
while time.time() < deadline:
    time.sleep(10)
    names = str(a.list_dir(OUT))
    if "spike-done" in names:
        break
    print("  ...", time.strftime("%H:%M:%S"))
else:
    print("TIMEOUT waiting for the run; partial logs follow")
log = a.read_file(OUT + "/spike-run.log")
if not isinstance(log, str):
    log = log.decode("latin-1", "replace")
print(log)
open(os.path.join(ROOT, "build", "amiga", f"spike-run-{TAG}.log"), "w").write(log)
