;;;; drive.lisp -- the host editor's unattended acceptance run, driven
;;;; through the editor's own TCP port (specs/clamacs-host.md, phase H2):
;;;; verify/realamiga/drive.rexx transcribed leg by leg, the same OK lines
;;;; and the same wants, minus what only an Amiga has (ARexx ports,
;;;; sendkey's raw keys, ENVARC:) -- each such leg is an INFO line here,
;;;; not a silent gap.  The Lisp the legs talk to is a SECOND clamiga
;;;; process: the editor starts it (`Start clamiga', the TCP transport of
;;;; phase H5) on the binary it runs on, so the integration,
;;;; introspection, REPL, debugger and inspector legs run against a
;;;; separate clamiga, and the own-Lisp leg switches to the editor itself
;;;; and back, as drive.rexx's phase 5 does on the Amiga.  The editor
;;;; stops that clamiga at its own exit; run-drive.sh checks its log.
;;;;
;;;;   clamiga --non-interactive --load verify/host/drive.lisp -- main
;;;;   clamiga --non-interactive --load verify/host/drive.lisp -- second
;;;;
;;;; MAIN drives the editor verify/host/run-drive.sh started on sample.lisp
;;;; and quits it; SECOND talks to the second editor the script starts
;;;; against the layout file MAIN wrote, checks where it came up and quits
;;;; it.  The environment says where things are:
;;;;
;;;;   CLAMACS_DRIVE_DIR   the editor's private directory (its clamacs-port
;;;;                       and clamacs-token files)
;;;;   CLAMACS_DRIVE_ROOT  the clamacs checkout, for the fixtures
;;;;   CLAMACS_DRIVE_TMP   a scratch directory: what RAM: is on the Amiga
;;;;   CLAMACS_DRIVE_CFG   the layout file the editor reads and writes
;;;;                       (~/.clamacs-windows.cfg of the run's own HOME)
;;;;
;;;; Every line printed lands in the run's log; run-drive.sh greps it for
;;;; FAIL and DRIVE-DONE.  This is a client of its own -- forty lines of
;;;; protocol, written without the editor's code -- so the run also proves
;;;; the port from the outside.

(defpackage :clamacs-drive (:use :cl))
(in-package :clamacs-drive)

(defvar *mode* (or (first ext:*command-line-args*) "main"))
(defvar *dir* (or (ext:getenv "CLAMACS_DRIVE_DIR") (error "CLAMACS_DRIVE_DIR is not set")))
(defvar *root* (or (ext:getenv "CLAMACS_DRIVE_ROOT") (error "CLAMACS_DRIVE_ROOT is not set")))
(defvar *tmp* (or (ext:getenv "CLAMACS_DRIVE_TMP") (error "CLAMACS_DRIVE_TMP is not set")))
(defvar *cfg* (or (ext:getenv "CLAMACS_DRIVE_CFG") (error "CLAMACS_DRIVE_CFG is not set")))

(defun fixture (name)
  (concatenate 'string *root* "verify/realamiga/" name))

(defun scratch (name)
  (concatenate 'string *tmp* name))

;;; ------------------------------------------------------------------
;;; The protocol
;;; ------------------------------------------------------------------

(defvar *port* nil "The connection.")
(defvar *rc* 0 "The last reply's rc, as ARexx's RC.")
(defvar *result* "" "The last reply's text, as ARexx's RESULT.")

(defun say (fmt &rest args)
  (format t "~?~%" fmt args)
  (finish-output))

(defun ok (fmt &rest args) (apply #'say (concatenate 'string "OK " fmt) args))
(defun fail (fmt &rest args) (apply #'say (concatenate 'string "FAIL " fmt) args))
(defun info (fmt &rest args) (apply #'say (concatenate 'string "INFO " fmt) args))

(defun check (test fmt-ok args-ok fmt-fail args-fail)
  (if test (apply #'ok fmt-ok args-ok) (apply #'fail fmt-fail args-fail)))

(defun file-line (path)
  "The file's first line without its newline, or NIL."
  (with-open-file (in path :if-does-not-exist nil)
    (and in (read-line in nil nil))))

(defun read-reply (stream)
  "(values RC TEXT) of a reply frame, or NIL when the connection is gone."
  (let ((header (read-line stream nil nil)))
    (when header
      (let ((blank (position #\Space header)))
        (when blank
          (let ((rc (parse-integer header :end blank :junk-allowed t))
                (n (parse-integer header :start (1+ blank) :junk-allowed t)))
            (when (and rc n)
              (let* ((text (make-string n))
                     (got (read-sequence text stream)))
                (and (= got n) (values rc text))))))))))

(defun send (stream line)
  (format stream "~D~%~A" (length line) line)
  (finish-output stream))

(defun try-connect ()
  "One attempt: an authenticated connection, or NIL."
  (let ((port (file-line (concatenate 'string *dir* "clamacs-port")))
        (token (file-line (concatenate 'string *dir* "clamacs-token"))))
    (when (and port token)
      (let ((stream (handler-case (ext:open-tcp-stream "127.0.0.1" (parse-integer port) 2)
                      (error () nil))))
        (when stream
          (send stream (concatenate 'string "AUTH " token))
          (multiple-value-bind (rc text) (read-reply stream)
            (cond ((and rc (= rc 0) (string= text "OK")) stream)
                  (t (close stream) nil))))))))

(defun connect (seconds)
  "Wait up to SECONDS for the port and connect to it."
  (let ((deadline (+ (get-universal-time) seconds)))
    (loop
      (let ((stream (try-connect)))
        (when stream (return stream)))
      (when (> (get-universal-time) deadline)
        (return nil))
      (sleep 0.5))))

(defun cmd (line)
  "LINE to the editor; *RC* and *RESULT* as ARexx would have them.  A
connection that is gone answers rc 20 and says so."
  (send *port* line)
  (multiple-value-bind (rc text) (read-reply *port*)
    (cond (rc (setq *rc* rc *result* text))
          (t (setq *rc* 20 *result* "(the editor's port is gone)"))))
  *result*)

(defun port-gone-p ()
  "Whether the editor has gone: its files are removed at shutdown and a
fresh connection is refused."
  (and (null (probe-file (concatenate 'string *dir* "clamacs-port")))
       (null (try-connect))))

(defun wait-gone (seconds)
  (let ((deadline (+ (get-universal-time) seconds)))
    (loop
      (when (port-gone-p) (return t))
      (when (> (get-universal-time) deadline) (return nil))
      (sleep 0.5))))

;;; ------------------------------------------------------------------
;;; Waiting for an answer (the WaitXxx procedures of drive.rexx)
;;; ------------------------------------------------------------------

(defun pause (ticks)
  "TICKS/50 s, as sendkey WAIT does."
  (sleep (/ ticks 50.0)))

(defun wait-echo (needle ticks)
  "The echo area, once it contains NEEDLE; \"\" after TICKS half-seconds."
  (dotimes (i ticks "")
    (cmd "STATUS")
    (when (and (= *rc* 0) (search needle *result*))
      (return *result*))
    (pause 25)))

(defun get-line ()
  "The cursor line as text, its newline taken off."
  (cmd "TE GETLINE")
  (if (/= *rc* 0)
      ""
      (string-right-trim '(#\Newline) *result*)))

(defun wait-line (needle ticks)
  (dotimes (i ticks "")
    (cmd "TE GETLINE")
    (when (and (= *rc* 0) (search needle *result*))
      (return *result*))
    (pause 25)))

(defun cursor-line ()
  (cmd "TE GETCURSOR LINE")
  (and (= *rc* 0) (parse-integer *result* :junk-allowed t)))

(defun wait-cursor (from ticks)
  "The cursor line once it is no longer FROM, or NIL."
  (dotimes (i ticks nil)
    (let ((y (cursor-line)))
      (when (and y (/= y from)) (return y)))
    (pause 25)))

(defun wait-cursor-past (y ticks)
  (dotimes (i ticks nil)
    (let ((now (cursor-line)))
      (when (and now (> now y)) (return now)))
    (pause 25)))

(defun wait-cursor-at (y ticks)
  (dotimes (i ticks nil)
    (let ((now (cursor-line)))
      (when (and now (= now y)) (return now)))
    (pause 25)))

(defun find-line (needle n)
  "Whether one of the first N lines of the active window contains NEEDLE.
Moves the cursor."
  (loop for i from 1 to n
        do (cmd (format nil "GOTOLINE ~D" i))
           (cmd "TE GETLINE")
           (when (and (= *rc* 0) (search needle *result*))
             (return t))))

(defun file-has-line (path want)
  (with-open-file (in path :if-does-not-exist nil)
    (and in
         (loop for line = (read-line in nil nil)
               while line
               thereis (string= (string-trim " " line) want)))))

(defun write-file (path text)
  (with-open-file (out path :direction :output :if-exists :supersede)
    (write-string text out)
    t))

(defun result-is (want) (and (= *rc* 0) (string= *result* want)))
(defun result-has (needle) (and (search needle *result*) t))

(defun file-has-prefix (path prefix)
  (with-open-file (in path :if-does-not-exist nil)
    (and in
         (loop for line = (read-line in nil nil)
               while line
               thereis (and (>= (length line) (length prefix))
                            (string= line prefix :end1 (length prefix)))))))

;;; The dock's panels (phase H3): what the editor told the page to show,
;;; and what the page says it shows, both read through EVAL.  The page's
;;; report follows the batch that changed it by one turn of the loop, so
;;; both are polled.

(defun wait-eval (form needle ticks)
  "EVAL FORM until its answer contains NEEDLE; \"\" after TICKS half-seconds."
  (dotimes (i ticks "")
    (cmd (concatenate 'string "EVAL " form))
    (when (and (= *rc* 0) (search needle *result*))
      (return *result*))
    (pause 25)))

(defun panel-state (panel needle &optional (ticks 20))
  "The editor's own account of PANEL once it says NEEDLE, or \"\"."
  (wait-eval (format nil "(clamacs::host-panel-state ~S)" panel) needle ticks))

(defun escape-quotes (text)
  "TEXT as EVAL prints a string value: every quote escaped."
  (with-output-to-string (out)
    (loop for c across text
          do (when (char= c #\") (write-char #\\ out))
             (write-char c out))))

(defun page-panels (needle &optional (ticks 20))
  "The page's report once it says NEEDLE (JSON text, spelled unescaped
here), or \"\"."
  (wait-eval "(clamacs::host-page-panels)" (escape-quotes needle) ticks))

(defun menu-index (command)
  "The table index of COMMAND's menu item, asked of the editor."
  (cmd (format nil "EVAL (clamacs::menu-find ~S)" command))
  (and (= *rc* 0) (parse-integer *result* :junk-allowed t)))

(defun page-menu-disabled ()
  "The indices the page's report lists as disabled: (values LIST FOUND-P),
FOUND-P NIL before the page reported anything."
  (cmd "EVAL (clamacs::host-page-panels)")
  (let* ((key "disabled\\\":[")
         (at (and (= *rc* 0) (search key *result*))))
    (if (null at)
        (values '() nil)
        (let* ((start (+ at (length key)))
               (end (position #\] *result* :start start)))
          (values (read-from-string
                   (concatenate 'string "(" (substitute #\Space #\, (subseq *result* start end)) ")"))
                  t)))))

(defun wait-page-menu (index enabled ticks)
  "Until the page's report shows the item at INDEX ENABLED (T) or dimmed
\(NIL); NIL after TICKS half-seconds."
  (dotimes (i ticks nil)
    (multiple-value-bind (disabled found) (page-menu-disabled)
      (when (and found (eq enabled (not (member index disabled))))
        (return t)))
    (pause 25)))

(defun check-panels (what state-needle page-needle)
  "WHAT is (panel step): one OK for the editor's account of the panel
and one for the page's report.  (SECOND is this file's own function --
the second editor's mode -- so the list is taken apart by hand.)"
  (destructuring-bind (panel step) what
    (let ((state (panel-state panel state-needle)))
      (if (string/= state "")
          (ok "~A: the editor shows the ~A panel ~A" step panel state-needle)
          (fail "~A: the editor's ~A panel says ~A (wanted ~A)" step panel *result* state-needle)))
    (let ((page (page-panels page-needle)))
      (if (string/= page "")
          (ok "~A: the page reports ~A" step page-needle)
          (fail "~A: the page reports ~A (wanted ~A)" step *result* page-needle)))))

;;; ------------------------------------------------------------------
;;; The main run
;;; ------------------------------------------------------------------

(defun leg-editor-checks ()
  ;; The port, and the CPU store question (the 68080 defect: a host has
  ;; no such CPU, but the leg is the same).
  (cmd "EVAL (if (member :cpu-lost-stores *features*) \"LOST-STORES\" \"STORES-OK\")")
  (if (result-has "STORES-OK")
      (ok "the editor keeps its stores on this launch")
      (info "the editor answered the CPU store question with: ~A" *result*))

  (cmd "GETFILE")
  (if (and (= *rc* 0) (result-has "sample.lisp"))
      (ok "GETFILE ~A" *result*)
      (fail "GETFILE rc= ~D result= ~A" *rc* *result*))

  ;; GOTOLINE is 1-based, the class's GETCURSOR 0-based.
  (cmd "GOTOLINE 3")
  (if (= *rc* 0) (ok "GOTOLINE") (fail "GOTOLINE rc= ~D" *rc*))
  (cmd "TE GETCURSOR LINE")
  (if (result-is "2")
      (ok "GOTOLINE 3 put the cursor on CursorY ~A" *result*)
      (fail "CURSOR rc= ~D CursorY= ~A" *rc* *result*))

  (cmd "EVAL end-of-buffer")
  (if (= *rc* 0) (ok "EVAL end-of-buffer") (fail "EVAL rc= ~D" *rc*))
  (cmd "EVAL beginning-of-buffer")
  (cmd "TE GETCURSOR LINE")
  (if (result-is "0")
      (ok "beginning-of-buffer moved to CursorY ~A" *result*)
      (fail "beginning-of-buffer CursorY= ~A" *result*))

  (cmd "GOTOLINE 6")
  (cmd "EVAL beginning-of-defun")
  (cmd "TE GETCURSOR LINE")
  (if (result-is "2")
      (ok "beginning-of-defun found the defun at CursorY ~A" *result*)
      (fail "beginning-of-defun CursorY= ~A" *result*))
  (cmd "EVAL end-of-defun")
  (cmd "TE GETCURSOR LINE")
  (if (result-is "7")
      (ok "end-of-defun reached CursorY ~A" *result*)
      (fail "end-of-defun CursorY= ~A" *result*))

  (cmd "EVAL no-such-command")
  (if (string= *result* "unknown command")
      (ok "unknown command rejected")
      (fail "unknown command gave ~A" *result*))

  ;; The live-hacking door: a form, what it printed in front of its value.
  (cmd "EVAL (progn (princ \"printed\") 42)")
  (if (and (= *rc* 0) (result-has "printed") (result-has "42"))
      (ok "EVAL of a form answered with what it printed and its value")
      (fail "EVAL of a printing form gave rc= ~D result= ~A" *rc* *result*))
  (cmd "EVAL (room)")
  (if (and (= *rc* 0) (result-has "Heap:") (result-has "bytes free"))
      (ok "EVAL (room) reported the editor heap, ~D characters" (length *result*))
      (fail "EVAL (room) gave rc= ~D result= ~A" *rc* *result*))

  (cmd "EVAL end-of-buffer")
  (cmd "INSERT (list 1 2 3)")
  (cmd "TE GETLINE")
  (if (result-has "(list 1 2 3)")
      (ok "INSERT and GETLINE round trip")
      (fail "GETLINE gave ~A" *result*))
  (cmd "EVAL backward-sexp")
  (cmd "TE GETCURSOR COLUMN")
  (if (result-is "0")
      (ok "backward-sexp landed on the open paren, column ~A" *result*)
      (fail "backward-sexp column= ~A" *result*))

  (cmd (format nil "OPEN FILE ~A LINE 2" (fixture "sample2.lisp")))
  (if (= *rc* 0) (ok "OPEN second file") (fail "OPEN rc= ~D" *rc*))
  (cmd "GETFILE")
  (if (result-has "sample2.lisp")
      (ok "second document is active ~A" *result*)
      (fail "active document is ~A" *result*))

  (cmd "EVAL kill-buffer")
  (cmd "GETFILE")
  (if (not (result-has "sample2.lisp"))
      (ok "kill-buffer closed the second document; the active document is now ~A" *result*)
      (fail "kill-buffer left ~A active" *result*))
  (cmd (format nil "OPEN FILE ~A LINE 2" (fixture "sample2.lisp")))
  (cmd "GETFILE")
  (if (and (= *rc* 0) (result-has "sample2.lisp"))
      (ok "the second document is open again after kill-buffer")
      (fail "reopening after kill-buffer gave rc= ~D active= ~A" *rc* *result*)))

(defun leg-menu ()
  (cmd "MENU find-file STATE")
  (if (string= *result* "enabled")
      (ok "the menu strip has Open")
      (fail "MENU find-file STATE gave ~A" *result*))
  (cmd "MENU forward-char STATE")
  (if (string= *result* "no such menu item")
      (ok "forward-char is not a menu item")
      (fail "MENU forward-char STATE gave ~A" *result*))

  (let ((file (scratch "clamacs-menu-test.lisp")))
    (cmd (format nil "OPEN FILE ~A" file))
    (cmd "MENU save-buffer STATE")
    (if (string= *result* "disabled")
        (ok "Save is dimmed for a clean buffer")
        (fail "Save on a clean buffer is ~A" *result*))
    ;; The page's own menu bar, not only the editor's account of it
    (let ((save (menu-index "save-buffer")))
      (if (and save (wait-page-menu save nil 20))
          (ok "the page's menu bar dims Save (item ~D)" save)
          (fail "the page's menu bar does not dim Save (item ~A): ~A" save *result*))
      (cmd "INSERT (defun menu-test () 42)")
      (cmd "MENU save-buffer STATE")
      (if (string= *result* "enabled")
          (ok "the first edit enabled Save")
          (fail "Save after an edit is ~A" *result*))
      (if (and save (wait-page-menu save t 20))
          (ok "the page's menu bar enabled Save after the edit")
          (fail "the page's menu bar still dims Save: ~A" *result*)))
    (cmd "MENU save-buffer")
    (if (and (= *rc* 0) (string= *result* "") (probe-file file))
        (ok "the menu saved the buffer")
        (fail "MENU save-buffer rc= ~D result= ~A exists= ~A" *rc* *result* (and (probe-file file) t)))
    (cmd "MENU save-buffer STATE")
    (if (string= *result* "disabled")
        (ok "Save dimmed after the menu saved")
        (fail "Save after the save is ~A" *result*))
    (cmd "MENU kill-buffer")
    (cmd "GETFILE")
    (if (not (result-has "clamacs-menu-test"))
        (ok "Close Buffer closed it; the active document is now ~A" *result*)
        (fail "Close Buffer left ~A active" *result*)))

  (cmd (format nil "OPEN FILE ~A" (fixture "sample.lisp")))
  (cmd "GOTOLINE 6")
  (cmd "MENU beginning-of-defun")
  (cmd "TE GETCURSOR LINE")
  (if (result-is "2")
      (ok "the menu ran beginning-of-defun, CursorY ~A" *result*)
      (fail "the menu pick left CursorY= ~A" *result*))
  (cmd "MENU clamacs-repl-clear STATE")
  (if (string= *result* "disabled")
      (ok "Clear Transcript is dimmed outside the REPL")
      (fail "Clear Transcript in a file buffer is ~A" *result*))
  (cmd "MENU clamacs-hyperspec STATE")
  (if (string= *result* "enabled")
      (ok "the Help menu has the HyperSpec")
      (fail "MENU clamacs-hyperspec STATE gave ~A" *result*))
  ;; About is a native requester, which a script cannot dismiss: its text
  ;; is asked for instead.  The toolkit lines name what the window is made
  ;; of, which proves the webview library answered its version.
  (cmd "MENU clamacs-about STATE")
  (if (string= *result* "enabled")
      (ok "the Project menu has About")
      (fail "MENU clamacs-about STATE gave ~A" *result*))
  ;; The first line is the shim's, one per host (the Cocoa, GTK or Win32
  ;; body of host/clamacs-host.m); the second is webview's version and
  ;; the WebKit token of the user agent, the same everywhere.
  (cmd "EVAL (clamacs::about-text clamacs::*editor*)")
  (if (and (= *rc* 0)
           (or (search "Cocoa/WebKit on macOS" *result*)
               (search "GTK " *result*)
               (search "Win32/WebView2 on Windows" *result*))
           (search "webview " *result*) (search ", WebKit " *result*)
           (not (search "unknown" *result*)))
      (ok "About names the toolkit: ~A"
          (substitute #\| #\Newline (subseq *result* 0 (min 160 (length *result*)))))
      (fail "About's toolkit lines: ~A" *result*)))

(defun buffers-lines ()
  "BUFFERS as a list of lines."
  (cmd "BUFFERS")
  (let ((lines '()) (start 0) (text *result*))
    (loop
      (let ((nl (position #\Newline text :start start)))
        (push (subseq text start nl) lines)
        (if nl (setq start (1+ nl)) (return))))
    (nreverse lines)))

(defun leg-buffers ()
  (let ((b (buffers-lines)))
    (if (and (member "> sample.lisp" b :test #'string=)
             (member "  sample2.lisp" b :test #'string=))
        (ok "the Buffers menu lists the files, sample.lisp ticked")
        (fail "BUFFERS gave ~{~A~^|~}" b)))
  (cmd "BUFFERS sample2.lisp")
  (let ((r *result*))
    (cmd "GETFILE")
    (if (and (string= r "") (result-has "sample2.lisp"))
        (ok "picking sample2.lisp in the Buffers menu activated it")
        (fail "BUFFERS sample2.lisp gave ~A, active ~A" r *result*)))
  (let ((b (buffers-lines)))
    (if (and (member "> sample2.lisp" b :test #'string=)
             (not (member "> sample.lisp" b :test #'string=)))
        (ok "the tick moved to sample2.lisp")
        (fail "after the pick BUFFERS gave ~{~A~^|~}" b)))
  ;; The page's Buffers menu shows the same lines, the tick included
  (if (string/= (page-panels "\"> sample2.lisp\"") "")
      (ok "the page's Buffers menu ticks sample2.lisp")
      (fail "the page's Buffers menu: ~A" *result*))
  (if (string/= (page-panels "\"  sample.lisp\"") "")
      (ok "the page's Buffers menu lists sample.lisp unticked")
      (fail "the page's Buffers menu: ~A" *result*))
  (cmd "MENU clamacs-room")
  (let* ((b (buffers-lines))
         (bar (position "-" b :test #'string=))
         (room (position "> *clamacs-room*" b :test #'string=))
         (sample (position "  sample.lisp" b :test #'string=)))
    (if (and bar room sample (> room bar) (< sample bar))
        (ok "*clamacs-room* is a tool buffer below the bar")
        (fail "with *clamacs-room* open BUFFERS gave ~{~A~^|~}" b)))
  (cmd "BUFFERS nothing-by-that-name")
  (if (string= *result* "no such buffer")
      (ok "BUFFERS refused an unknown buffer")
      (fail "BUFFERS nothing-by-that-name gave ~A" *result*))
  (cmd "MENU kill-buffer")
  (let ((b (buffers-lines)))
    (if (not (find "*clamacs-room*" b :test #'search))
        (ok "a closed buffer left the Buffers menu")
        (fail "after kill-buffer BUFFERS gave ~{~A~^|~}" b)))
  (cmd "BUFFERS sample.lisp"))

(defun leg-keys ()
  (cmd (format nil "OPEN FILE ~A" (fixture "sample.lisp")))
  (cmd "EVAL beginning-of-buffer")
  (cmd "KEY C-x")
  (cmd "STATUS")
  (if (string= *result* "C-x -")
      (ok "C-x is pending and echoed as ~A" *result*)
      (fail "C-x echoed ~A" *result*))
  (cmd "KEY C-g")
  (cmd "STATUS")
  (if (string= *result* "Quit")
      (ok "C-g cancelled the prefix")
      (fail "C-g gave ~A" *result*))
  (cmd "KEY C-x C-q")
  (cmd "STATUS")
  (if (result-has "undefined")
      (ok "C-x C-q reported: ~A" *result*)
      (fail "C-x C-q gave ~A" *result*))
  (cmd "EVAL beginning-of-buffer")
  (cmd "KEY C-u 4 C-n")
  (cmd "TE GETCURSOR LINE")
  (if (result-is "4")
      (ok "C-u 4 C-n moved four lines, CursorY ~A" *result*)
      (fail "C-u 4 C-n CursorY= ~A" *result*))
  (cmd "KEY M-<")
  (cmd "TE GETCURSOR LINE")
  (if (result-is "0")
      (ok "M-< reached the top")
      (fail "M-< CursorY= ~A" *result*))
  ;; The kill ring.
  (cmd "EVAL beginning-of-buffer")
  (let ((first-line (cmd "TE GETLINE")))
    (cmd "KEY C-SPC")
    (cmd "KEY C-n")
    (cmd "KEY C-w")
    (cmd "EVAL beginning-of-buffer")
    (cmd "TE GETLINE")
    (if (string/= *result* first-line)
        (ok "C-w killed the first line")
        (fail "C-w did not change the buffer"))
    (cmd "KEY C-y")
    (cmd "EVAL beginning-of-buffer")
    (cmd "TE GETLINE")
    (if (string= *result* first-line)
        (ok "C-y yanked it back: ~A" (string-right-trim '(#\Newline) *result*))
        (fail "C-y gave ~A" *result*)))
  (cmd "KEY M-x")
  (cmd "STATUS")
  (cmd "KEY C-g")
  (cmd "STATUS")
  (if (string= *result* "Quit")
      (ok "M-x opened the minibuffer and C-g closed it")
      (fail "minibuffer C-g gave ~A" *result*))
  (cmd "GOTOLINE 6")
  (cmd "TE POSITION SOL")
  (cmd "KEY TAB")
  (cmd "TE GETCURSOR COLUMN")
  (if (result-is "4")
      (ok "TAB indented the (when ...) line to column ~A" *result*)
      (fail "TAB put the cursor at column ~A" *result*))
  (info "the raw-key leg (sendkey, Alt as Meta under MUI) has no host twin here: verify/host/host-keys.sh types through the page"))

(defvar *want* "doc1 100 120 640 400"
  "Where the second editor's first window must come up.")

(defun leg-snapshot ()
  (cmd "EVAL clamacs-show-errors")
  (cmd (format nil "OPEN FILE ~A" (fixture "sample.lisp")))
  (pause 10)
  (cmd "GETWINDOW")
  (let* ((place *result*)
         (words (let ((out '()) (start 0))
                  (loop
                    (let ((blank (position #\Space place :start start)))
                      (push (subseq place start blank) out)
                      (if blank (setq start (1+ blank)) (return))))
                  (nreverse out)))
         (numbers (mapcar (lambda (w) (parse-integer w :junk-allowed t)) (cdr words))))
    (if (and (= *rc* 0) (= (length words) 5) (string= (first words) "doc1")
             (every #'integerp numbers) (> (third numbers) 0) (> (fourth numbers) 0))
        (ok "GETWINDOW answered ~A" place)
        (fail "GETWINDOW gave ~A" place))
    (cmd "EVAL clamacs-snapshot-windows")
    (cmd "STATUS")
    (if (result-has "Saved the positions")
        (ok "the snapshot was taken: ~A" *result*)
        (fail "clamacs-snapshot-windows said ~A" *result*))
    (if (probe-file *cfg*)
        (ok "the snapshot wrote ~A" *cfg*)
        (fail "after the snapshot there is no ~A" *cfg*))
    (info "ENVARC: is the Amiga's; the host has the one file")
    (if (file-has-line *cfg* place)
        (ok "the file holds the active window as ~A" place)
        (fail "no line ~A in ~A" place *cfg*))
    ;; The error list is a panel of the dock here: clamacs-show-errors
    ;; opened the dock, so the file holds the dock and the panel.
    (if (file-has-prefix *cfg* "errors ")
        (ok "the file holds the error list")
        (fail "no errors line in ~A" *cfg*))
    (if (file-has-prefix *cfg* "dock ")
        (ok "the file holds the dock")
        (fail "no dock line in ~A" *cfg*))
    (check-panels '(:diagnostics "clamacs-show-errors") "open rows 0" "\"diagnostics\":{\"open\":true,\"rows\":0")
    ;; The file the second editor (run-drive.sh, the SECOND mode below)
    ;; comes up against.
    (if (write-file *cfg* (format nil "; written by drive.lisp~%~%~A~%" *want*))
        (ok "wrote a file of our own: ~A" *want*)
        (fail "could not write ~A" *cfg*))))

(defun leg-integration ()
  (cmd (format nil "OPEN FILE ~A" (fixture "eval.lisp")))
  (cmd "EVAL end-of-buffer")
  (cmd "STATUS")
  (let ((before *result*) (answer "") (last "") (n 0))
    (cmd "EVAL clamacs-eval-last-sexp")
    ;; The first eval attaches the REPL, which loads dev-repl into the
    ;; clamiga the editor started.
    (dotimes (i 240)
      (pause 25)
      (setq n (1+ i))
      (cmd "STATUS")
      (when (string= *result* "3")
        (setq answer *result*)
        (return))
      (when (and (string/= *result* before) (string/= *result* ""))
        (setq last *result*)))
    (if (string= answer "3")
        (ok "eval-last-sexp on (+ 1 2) echoed ~A after ~D / 2 s (the first eval attaches the REPL)" answer n)
        (fail "eval-last-sexp echoed ~A" last)))
  (cmd "GETNAME")
  (if (string= *result* "eval.lisp")
      (ok "the buffer eval left eval.lisp active: ~A" *result*)
      (fail "after the buffer eval the active window is ~A" *result*))
  (cmd "MENU clamacs-eval-defun STATE")
  (if (string= *result* "enabled")
      (ok "the Clamiga menu woke up with the port")
      (fail "Eval Defun with a port is ~A" *result*))
  (cmd "MENU run-lisp STATE")
  (if (string= *result* "disabled")
      (ok "Start clamiga is dimmed while connected")
      (fail "Start clamiga while connected is ~A" *result*))

  (cmd (format nil "OPEN FILE ~A" (fixture "errors.lisp")))
  (cmd "STATUS")
  (cmd "EVAL clamacs-load-buffer")
  (cmd "GETFILE")
  (if (result-has "errors.lisp")
      (ok "the editor answered while a load was in flight")
      (fail "editor did not answer during a load: ~A" *result*))
  (let ((diags (wait-echo "error(s)" 120)))
    (if (search "2 error(s)" diags)
        (ok "clamacs-load-buffer reported ~A" diags)
        (fail "load-buffer diagnostics were ~A" diags)))
  ;; What the load printed (clamiga's own report of the first error) came
  ;; back in the reply's log and went into the REPL transcript, under the
  ;; reply's `; loading' line; the buffer kept the focus.
  (cmd "EVAL (let ((repl (clamacs::repl-doc clamacs::*editor*))) (and repl (clamacs::doc-text repl 0 (clamacs::doc-end repl))))")
  (if (and (result-has "; loading") (result-has "first deliberate error"))
      (ok "the load's output went into the REPL transcript")
      (fail "the REPL transcript after the load is ~A" *result*))
  (cmd "GETNAME")
  (if (result-has "errors.lisp")
      (ok "the buffer kept the focus over the transcript: ~A" *result*)
      (fail "after the load the active window is ~A" *result*))
  (cmd "MENU clamacs-next-error STATE")
  (if (string= *result* "enabled")
      (ok "Next Error woke up with the diagnostics")
      (fail "Next Error with two diagnostics is ~A" *result*))
  (check-panels '(:diagnostics "the load's diagnostics") "open rows 2 selected none"
                "\"diagnostics\":{\"open\":true,\"rows\":2,\"selected\":null")
  (cmd "EVAL clamacs-next-error")
  (cmd "TE GETCURSOR LINE")
  (if (result-is "6")
      (ok "next-error jumped to the first error, CursorY ~A" *result*)
      (fail "next-error CursorY= ~A" *result*))
  (check-panels '(:diagnostics "next-error") "open rows 2 selected 0"
                "\"diagnostics\":{\"open\":true,\"rows\":2,\"selected\":0")
  (cmd "EVAL clamacs-next-error")
  (cmd "TE GETCURSOR LINE")
  (if (result-is "8")
      (ok "next-error jumped to the second error, CursorY ~A" *result*)
      (fail "second next-error CursorY= ~A" *result*))
  (cmd "EVAL clamacs-next-error")
  (cmd "STATUS")
  (if (result-has "No further")
      (ok "next-error stopped at the last diagnostic: ~A" *result*)
      (fail "next-error past the end gave ~A" *result*))
  (cmd "EVAL clamacs-previous-error")
  (cmd "TE GETCURSOR LINE")
  (if (result-is "6")
      (ok "previous-error went back to CursorY ~A" *result*)
      (fail "previous-error CursorY= ~A" *result*)))

(defun leg-introspection ()
  (let ((intro (fixture "intro.lisp")))
    (cmd (format nil "OPEN FILE ~A" intro))
    (pause 25)
    (cmd "EVAL clamacs-load-buffer")
    (let ((loaded (wait-echo "error(s)" 120)))
      (if (eql (search "0 error(s)" loaded) 0)
          (ok "intro.lisp loaded: ~A" loaded)
          (fail "intro.lisp load reported ~A" loaded)))

    ;; The idle timer: the arglist is cached before it is asked for.
    (cmd "GOTOLINE 24")
    (cmd "TE POSITION SOL")
    (cmd "KEY C-u 8 C-f")
    (pause 150)
    (cmd "EVAL clamacs-arglist")
    (cmd "STATUS")
    (let ((args *result*))
      (cond ((string= args "(twice n)")
             (ok "the idle timer had the arglist ready: ~A" args))
            ((string/= (wait-echo "(twice n)" 40) "")
             (fail "the arglist came only when asked for -- the idle timer had not cached it"))
            (t (fail "clamacs-arglist gave ~A" args))))

    ;; M-. and M-,
    (cmd "TE POSITION SOL")
    (cmd "KEY C-f")
    (let ((from (cursor-line)))
      (cmd "KEY M-.")
      (let ((landed (wait-cursor from 40)))
        (cmd "GETFILE")
        (if (and (eql landed 8) (string-equal *result* intro))
            (ok "M-. jumped to the definition of twice, CursorY ~A" landed)
            (fail "M-. put the cursor at CursorY ~A in ~A" landed *result*)))
      (cmd "KEY M-,")
      (let ((back (cursor-line)))
        (if (eql back from)
            (ok "M-, returned to CursorY ~A" back)
            (fail "M-, went to CursorY ~A (wanted ~A)" back from))))

    ;; Macroexpansion.
    (cmd (format nil "OPEN FILE ~A" intro))
    (pause 25)
    (cmd "GOTOLINE 22")
    (cmd "KEY C-c RET")
    (let ((line (wait-line "(with-twice z 4 z)" 40)))
      (cmd "GETNAME")
      (if (and (string/= line "") (string= *result* "*clamacs-macroexpansion*"))
          (ok "C-c RET expanded once into ~A: ~A" *result* (string-right-trim '(#\Newline) line))
          (fail "C-c RET gave ~A in window ~A" line *result*)))
    (cmd (format nil "OPEN FILE ~A" intro))
    (pause 25)
    (cmd "GOTOLINE 22")
    (cmd "KEY C-c M-m")
    (let ((line (wait-line "(let ((z (twice 4))) z)" 40)))
      (if (string/= line "")
          (ok "C-c M-m expanded fully: ~A" (string-right-trim '(#\Newline) line))
          (fail "C-c M-m did not show the full expansion")))

    ;; DESCRIBE.
    (cmd (format nil "OPEN FILE ~A" intro))
    (pause 25)
    (cmd "GOTOLINE 24")
    (cmd "KEY C-f")
    (cmd "KEY C-c C-d d")
    (cmd "STATUS")
    (if (result-has "Describe symbol")
        (ok "C-c C-d d prompted: ~A" *result*)
        (fail "C-c C-d d gave ~A" *result*))
    (cmd "KEY RET")
    (let ((line (wait-line "is a SYMBOL" 40)))
      (cmd "GETNAME")
      (if (and (search "TWICE" (string-upcase line)) (string= *result* "*clamacs-description*"))
          (ok "DESCRIBE opened ~A: ~A" *result* (string-right-trim '(#\Newline) line))
          (fail "DESCRIBE gave ~A in window ~A" line *result*)))
    (if (find-line "Documentation: Twice N." 12)
        (ok "the description carries the docstring")
        (fail "no docstring in the description"))

    ;; APROPOS.
    (cmd (format nil "OPEN FILE ~A" intro))
    (pause 25)
    (cmd "GOTOLINE 7")
    (cmd "KEY C-c C-d a")
    (cmd "STATUS")
    (if (result-has "Apropos")
        (ok "C-c C-d a prompted: ~A" *result*)
        (fail "C-c C-d a gave ~A" *result*))
    (cmd "KEY t w i c e RET")
    (let ((line (wait-line "twice" 40)))
      (cmd "GETNAME")
      (if (and (string/= line "") (string= *result* "*clamacs-apropos*"))
          (ok "APROPOS opened ~A: ~A" *result* (string-right-trim '(#\Newline) line))
          (fail "APROPOS gave ~A in window ~A" line *result*)))
    (if (and (find-line "twice function" 8) (find-line "with-twice macro" 8))
        (ok "APROPOS tagged the function and the macro")
        (fail "APROPOS did not list twice as a function and with-twice as a macro"))

    ;; Completion, in sample2.lisp.
    (cmd (format nil "OPEN FILE ~A" (fixture "sample2.lisp")))
    (pause 25)
    (cmd "EVAL end-of-buffer")
    (cmd "KEY RET")
    (cmd "INSERT twice-a")
    (cmd "KEY M-TAB")
    (let ((done (wait-echo "Sole completion" 40)))
      (cmd "TE GETLINE")
      (if (and (string/= done "") (result-has "twice-again"))
          (ok "M-TAB completed twice-a in place: ~A" (string-right-trim '(#\Newline) *result*))
          (fail "M-TAB gave ~A and the line ~A" done *result*)))
    (cmd "KEY RET")
    (cmd "INSERT twic")
    (cmd "KEY C-M-i")
    (if (string/= (wait-echo "Complete:" 40) "")
        (ok "C-M-i handed the candidates to the minibuffer")
        (fail "C-M-i on twic did not prompt"))
    (cmd "KEY TAB")
    (cmd "STATUS")
    (if (and (result-has "3 completions") (result-has "twice-again"))
        (ok "TAB listed them: ~A" *result*)
        (fail "TAB in the minibuffer gave ~A" *result*))
    (cmd "KEY - a TAB")
    (cmd "STATUS")
    (if (result-has "Sole completion")
        (ok "TAB narrowed twice-a to one")
        (fail "narrowing gave ~A" *result*))
    (cmd "KEY RET")
    (cmd "TE GETLINE")
    (if (result-has "twice-again")
        (ok "RET put the completion in the buffer: ~A" (string-right-trim '(#\Newline) *result*))
        (fail "after RET the line is ~A" *result*))))

(defun leg-repl ()
  (let ((intro (fixture "intro.lisp")))
    (cmd (format nil "OPEN FILE ~A" intro))
    (pause 25)
    (cmd "KEY C-c C-z")
    (cmd "GETNAME")
    (cond ((string= *result* "*clamacs-repl*")
           (ok "C-c C-z opened ~A" *result*)
           (cmd "MENU clamacs-repl-clear STATE")
           (if (string= *result* "enabled")
               (ok "Clear Transcript is live in the REPL window")
               (fail "Clear Transcript in the REPL window is ~A" *result*)))
          (t (fail "C-c C-z gave window ~A" *result*)))
    (wait-line "CL-USER> " 240)
    (if (string= (get-line) "CL-USER> ")
        (ok "the REPL prompt arrived: ~A" (get-line))
        (progn (cmd "STATUS")
               (fail "no REPL prompt; the cursor line is ~A and the echo area says ~A" (get-line) *result*)))

    ;; RET evaluates.
    (let ((p (cursor-line)))
      (cmd "INSERT (+ 1 2)")
      (cmd "KEY RET")
      (let ((y (wait-cursor-at (+ p 2) 40)))
        (cmd (format nil "GOTOLINE ~D" (+ p 2)))
        (let ((l (get-line)))
          (if (and y (string= l "3"))
              (ok "RET evaluated (+ 1 2) at the prompt: ~A" l)
              (fail "the line after (+ 1 2) is ~A (cursor ~A)" l y))))
      (cmd (format nil "GOTOLINE ~D" (+ p 3)))
      (let ((l (get-line)))
        (if (string= l "CL-USER> ")
            (ok "a new prompt followed the value")
            (fail "after the value came ~A" l)))
      (cmd "EVAL end-of-buffer"))

    ;; Streamed output.
    (let ((p (cursor-line)))
      (cmd "INSERT (progn (princ 'hello) (terpri) (princ 'there) 42)")
      (cmd "KEY RET")
      (let ((y (wait-cursor-at (+ p 4) 40)))
        (cmd (format nil "GOTOLINE ~D" (+ p 2)))
        (let ((l1 (get-line)))
          (cmd (format nil "GOTOLINE ~D" (+ p 3)))
          (let ((l2 (get-line)))
            (cmd (format nil "GOTOLINE ~D" (+ p 4)))
            (let ((l3 (get-line)))
              (if (and y (string= l1 "HELLO") (string= l2 "THERE") (string= l3 "42"))
                  (ok "output was streamed line by line before the value: ~A ~A ~A" l1 l2 l3)
                  (fail "streamed output gave ~A / ~A / ~A (cursor ~A)" l1 l2 l3 y))))))
      (cmd "EVAL end-of-buffer"))

    ;; READ-LINE.
    (let ((p (cursor-line)))
      (cmd "INSERT (read-line)")
      (cmd "KEY RET")
      (let ((asked (wait-echo "reading a line" 40)))
        (if (string/= asked "")
            (ok "READLINE armed the input: ~A" asked)
            (fail "READLINE did not arm the input")))
      (cmd "INSERT abc")
      (cmd "KEY RET")
      (let ((y (wait-cursor-past (+ p 2) 40)))
        (cmd (format nil "GOTOLINE ~D" (+ p 3)))
        (let ((l (get-line)))
          (if (and y (search "\"abc\"" l))
              (ok "RET answered READ-LINE and the value came back: ~A" l)
              (fail "after the READ-LINE answer came ~A (cursor ~A)" l y))))
      (cmd "EVAL end-of-buffer"))

    ;; C-c C-c interrupts.
    (let ((p (cursor-line)))
      (cmd "INSERT (loop)")
      (cmd "KEY RET")
      (pause 50)
      (cmd "KEY C-c C-c")
      (let ((y (wait-cursor-at (+ p 2) 60)))
        (cmd (format nil "GOTOLINE ~D" (+ p 2)))
        (let ((l (get-line)))
          (if (and y (search "Interrupted" l))
              (ok "C-c C-c interrupted (loop): ~A" l)
              (fail "the interrupt gave ~A (cursor ~A)" l y))))
      (cmd "EVAL end-of-buffer"))

    ;; A separate process: the editor's package is not there.
    (let ((p (cursor-line)))
      (cmd "INSERT (find-package :clamacs)")
      (cmd "KEY RET")
      (let ((y (wait-cursor-at (+ p 2) 40)))
        (cmd (format nil "GOTOLINE ~D" (+ p 2)))
        (let ((l (get-line)))
          (if (and y (string= l "NIL"))
              (ok "the REPL runs in a clamiga of its own: no CLAMACS package there")
              (fail "(find-package :clamacs) at the clamiga REPL gave ~A (cursor ~A)" l y))))
      (cmd "EVAL end-of-buffer"))

    ;; IN-PACKAGE moves the prompt.
    (cmd "INSERT (in-package :ext.dev)")
    (cmd "KEY RET")
    (if (string/= (wait-line "EXT.DEV> " 40) "")
        (ok "the prompt followed IN-PACKAGE: ~A" (get-line))
        (fail "the prompt did not change package"))
    (cmd "INSERT (in-package :cl-user)")
    (cmd "KEY RET")
    (if (string/= (wait-line "CL-USER> " 40) "")
        (ok "and back to ~A" (get-line))
        (fail "the prompt did not come back to CL-USER"))

    ;; History.
    (cmd "KEY M-p")
    (let ((l (get-line)))
      (if (search "(in-package :cl-user)" l)
          (ok "M-p brought back the last input: ~A" l)
          (fail "M-p gave ~A" l)))
    (cmd "KEY M-p")
    (let ((l (get-line)))
      (if (search "(in-package :ext.dev)" l)
          (ok "a second M-p went one further back")
          (fail "the second M-p gave ~A" l)))
    (cmd "KEY M-n")
    (cmd "KEY M-n")
    (let ((l (get-line)))
      (if (string= l "CL-USER> ")
          (ok "M-n came back to the empty input")
          (fail "M-n left ~A" l)))

    ;; The port stays free while a form runs.
    (cmd "INSERT (sleep 6)")
    (cmd "KEY RET")
    (cmd (format nil "OPEN FILE ~A" intro))
    (pause 10)
    (cmd "EVAL end-of-buffer")
    (cmd "KEY RET")
    (cmd "INSERT (twice-again 1")
    (cmd "EVAL clamacs-arglist")
    (let ((args (wait-echo "(twice-again n)" 8)))
      (if (string/= args "")
          (ok "the port answered ARGLIST while the REPL ran a form: ~A" args)
          (fail "no ARGLIST answer while the REPL was busy")))
    (cmd "KEY C-c C-z")
    (cmd "GETNAME")
    (let ((name *result*)
          (line (wait-line "CL-USER> " 40)))
      (if (and (string= name "*clamacs-repl*") (string/= line ""))
          (ok "C-c C-z raised the REPL again and (sleep 6) finished")
          (fail "back in ~A the cursor line is ~A" name line)))))

(defun leg-debugger ()
  (cmd "EVAL clamacs-repl")
  (cmd "EVAL end-of-buffer")
  (let ((p (cursor-line)))
    (cmd "INSERT (dbg-fn 3 4)")
    (cmd "KEY RET")
    (let ((echo (wait-echo "Debugger level 1, frame 0: ARG0 = 3" 60)))
      (if (string/= echo "")
          (ok "an error at the prompt opened the debugger: ~A" echo)
          (progn (cmd "STATUS")
                 (fail "no debugger for (dbg-fn 3 4); the echo area says ~A" *result*))))
    (cmd "MENU clamacs-debugger STATE")
    (if (string= *result* "enabled")
        (ok "the Debugger item woke up with the debugger")
        (fail "the Debugger item while debugging is ~A" *result*))
    (info "clamiga's own view (RESTARTS, BACKTRACE over its port) is the editor's own image here; not asked")
    ;; The dock's debugger panel: open on level 1 with frame 0 selected
    ;; and its locals in, on both sides of the page boundary.
    (check-panels '(:debugger "the debugger panel") "open level 1" "\"debugger\":{\"open\":true,\"level\":1,")
    ;; How many locals frame 0 has is the runtime's business (ARG0 and
    ;; ARG1 are among them); that there are some, and that frame 0 is the
    ;; one selected, is the panel's.
    (let ((state (panel-state :debugger "frame 0 locals ")))
      (if (and (string/= state "") (not (search "locals 0 " state)))
          (ok "the panel has the frames, frame 0 selected with its locals: ~A" state)
          (fail "the panel's frames and locals are ~A" *result*)))
    (let ((page (page-panels "\"frame\":0,\"locals\":")))
      (if (and (string/= page "") (not (search "\\\"locals\\\":0" page)))
          (ok "the page shows frame 0 selected with its locals")
          (fail "the page's debugger panel reports ~A" *result*)))
    (cmd "EVAL (clamacs::host-panel-state :dock)")
    (if (result-has "open")
        (ok "the dock is open: ~A" *result*)
        (fail "the dock says ~A" *result*))

    (cmd "KEY RET")
    (cmd "STATUS")
    (if (result-has "in the debugger")
        (ok "RET at the prompt is refused while debugging: ~A" *result*)
        (fail "RET while debugging gave ~A" *result*))

    (cmd "EVAL clamacs-debugger-eval")
    (cmd "STATUS")
    (if (result-has "Eval in frame 0")
        (ok "clamacs-debugger-eval prompted: ~A" *result*)
        (fail "clamacs-debugger-eval gave ~A" *result*))
    (cmd "KEY ( l i s t SPC a r g 0 SPC a r g 1 )")
    (cmd "KEY RET")
    (let ((y (wait-cursor-at (+ p 2) 40)))
      (cmd (format nil "GOTOLINE ~D" (+ p 2)))
      (let ((l (get-line)))
        (if (and y (string= l "(3 4)"))
            (ok "the frame eval saw the locals by name: ~A" l)
            (fail "the frame eval gave ~A (cursor ~A)" l y))))
    (cmd "EVAL end-of-buffer")

    (cmd "EVAL clamacs-debugger-eval")
    (cmd "KEY ( d b g - f n SPC 1 SPC 2 )")
    (cmd "KEY RET")
    (let ((echo (wait-echo "Debugger level 2, frame 0: ARG0 = 1" 40)))
      (if (string/= echo "")
          (ok "an error in the frame eval nested the debugger: ~A" echo)
          (progn (cmd "STATUS")
                 (fail "no nested debugger; the echo area says ~A" *result*))))
    (check-panels '(:debugger "the nested level") "open level 2" "\"debugger\":{\"open\":true,\"level\":2,")
    (cmd "EVAL clamacs-debugger-abort")
    (let ((echo (wait-echo "Debugger level 1, frame 0: ARG0 = 3" 40)))
      (if (string/= echo "")
          (ok "ABORT returned to level 1: ~A" echo)
          (progn (cmd "STATUS")
                 (fail "ABORT from level 2 left the echo area at ~A" *result*))))
    (check-panels '(:debugger "back at level 1") "open level 1" "\"debugger\":{\"open\":true,\"level\":1,")

    (cmd "EVAL clamacs-debugger-restart")
    (cmd "KEY 0")
    (cmd "KEY RET")
    (cond ((string/= (wait-line "CL-USER> " 40) "")
           (ok "RESTART 0 returned to the prompt")
           (cmd "MENU clamacs-debugger STATE")
           (if (string= *result* "disabled")
               (ok "the Debugger item dimmed with the restart")
               (fail "the Debugger item after the restart is ~A" *result*))
           (check-panels '(:debugger "after the restart") "closed level 0" "\"debugger\":{\"open\":false,"))
          (t (cmd "STATUS")
             (fail "no prompt after RESTART 0; the echo area says ~A" *result*)))
    (let ((q (cursor-line)))
      (cmd (format nil "GOTOLINE ~D" q))
      (let ((l (get-line)))
        (if (string= l "; Aborted")
            (ok "the transcript says the form was aborted: ~A" l)
            (fail "before the prompt came ~A" l))))
    (cmd "EVAL end-of-buffer"))

  ;; CONTINUE.
  (let ((p (cursor-line)))
    (cmd "INSERT (dbg-go-on)")
    (cmd "KEY RET")
    (let ((echo (wait-echo "Debugger level 1, frame 0" 60)))
      (if (string/= echo "")
          (ok "CERROR opened the debugger: ~A" echo)
          (progn (cmd "STATUS")
                 (fail "no debugger for (dbg-go-on); the echo area says ~A" *result*))))
    (cmd "EVAL clamacs-debugger-continue")
    (let ((line (wait-line "CL-USER> " 40)))
      (cmd (format nil "GOTOLINE ~D" (+ p 2)))
      (let ((l (get-line)))
        (if (and (string/= line "") (string= l ":WENT-ON"))
            (ok "CONTINUE let the form finish: ~A" l)
            (fail "after CONTINUE came ~A" l))))
    (cmd "EVAL end-of-buffer"))

  ;; A buffer eval reaches the debugger too.
  (cmd (format nil "OPEN FILE ~A" (scratch "clamacs-bufeval-test.lisp")))
  (cmd "STATUS")
  (if (string= *result* "(New file)")
      (ok "Open... on a name no file has made a new buffer: ~A" *result*)
      (fail "Open... on a new name said ~A" *result*))
  (cmd "INSERT (dbg-fn 5 6)")
  (cmd "EVAL clamacs-eval-last-sexp")
  (let ((echo (wait-echo "Debugger level 1, frame 0: ARG0 = 5" 60)))
    (if (string/= echo "")
        (ok "an error in a buffer eval opened the debugger: ~A" echo)
        (progn (cmd "STATUS")
               (fail "no debugger for the buffer eval of (dbg-fn 5 6); the echo area says ~A" *result*))))
  (cmd "EVAL clamacs-debugger-abort")
  (let ((echo (wait-echo "Aborted" 40)))
    (if (string/= echo "")
        (ok "Abort ended the buffer eval in its own echo area: ~A" echo)
        (progn (cmd "STATUS")
               (fail "after Abort the buffer's echo area says ~A" *result*))))
  (cmd "EVAL save-buffer")
  (cmd "EVAL kill-buffer")
  (cmd "EVAL clamacs-repl")
  (cmd "EVAL end-of-buffer"))

(defun leg-inspector ()
  (cmd "KEY C-c I")
  (cmd "STATUS")
  (if (result-has "Inspect value")
      (ok "C-c I prompted: ~A" *result*)
      (fail "C-c I gave ~A" *result*))
  (cmd "KEY ( l i s t SPC 1 SPC ( l i s t SPC 2 SPC 3 ) )")
  (cmd "KEY RET")
  (let ((echo (wait-echo "Inspecting CONS: (1 (2 3))" 40)))
    (if (string/= echo "")
        (ok "the inspector showed the object: ~A" echo)
        (progn (cmd "STATUS")
               (fail "the inspector did not answer; the echo area says ~A" *result*))))
  (check-panels '(:inspector "C-c I") "open type CONS depth 1 parts 2 object (1 (2 3))"
                "\"inspector\":{\"open\":true,\"type\":\"CONS\",\"depth\":1,\"object\":\"(1 (2 3))\",\"parts\":2")
  (cmd "EVAL clamacs-repl")
  (cmd "EVAL clamacs-inspector-part")
  (cmd "KEY 1")
  (cmd "KEY RET")
  (let ((echo (wait-echo "Inspecting CONS: ((2 3))" 40)))
    (if (string/= echo "")
        (ok "part 1 descended into the cdr: ~A" echo)
        (progn (cmd "STATUS")
               (fail "PART 1 gave ~A" *result*))))
  (check-panels '(:inspector "part 1") "open type CONS depth 2" "\"inspector\":{\"open\":true,\"type\":\"CONS\",\"depth\":2,")
  (cmd "EVAL clamacs-repl")
  (cmd "EVAL clamacs-inspector-pop")
  (let ((echo (wait-echo "Inspecting CONS: (1 (2 3))" 40)))
    (if (string/= echo "")
        (ok "Back came up to the list again: ~A" echo)
        (progn (cmd "STATUS")
               (fail "POP gave ~A" *result*))))
  (check-panels '(:inspector "Back") "open type CONS depth 1" "\"inspector\":{\"open\":true,\"type\":\"CONS\",\"depth\":1,")
  ;; The REPL is a tab of the dock too: raising it leaves the panels
  ;; open, the dock showing the REPL.
  (cmd "EVAL clamacs-repl")
  (cmd "GETNAME")
  (if (string= *result* "*clamacs-repl*")
      (ok "the REPL tab is active again")
      (fail "after clamacs-repl the active window is ~A" *result*))
  (check-panels '(:dock "the REPL tab") "open height" "\"dock\":{\"open\":true,\"shown\":\"doc"))

(defun leg-start-clamiga ()
  "`Start clamiga': the editor starts a second clamiga on the binary it
runs on, the token in the child's environment, and connects to it."
  (cmd "MENU clamacs-eval-defun STATE")
  (if (string= *result* "disabled")
      (ok "the Clamiga menu is dimmed while no clamiga is connected")
      (fail "Eval Defun without a clamiga is ~A" *result*))
  (cmd "MENU run-lisp STATE")
  (if (string= *result* "enabled")
      (ok "Start clamiga is live while no clamiga is connected")
      (fail "Start clamiga without a clamiga is ~A" *result*))
  ;; The pick returns once the clamiga's port is up (the launch waits for
  ;; its port file), or with the reason it is not.
  (cmd "MENU run-lisp")
  (cmd "STATUS")
  (if (string= *result* "Started clamiga")
      (ok "Start clamiga started a clamiga: ~A" *result*)
      (fail "Start clamiga said ~A" *result*))
  (cmd "EVAL (clamacs::tcp-transport-launched (clamacs::wire-home (clamacs::editor-wire clamacs::*editor*)))")
  (if (result-is "T")
      (ok "the wire's home transport knows it started that clamiga")
      (fail "the transport's launched flag is ~A" *result*))
  (cmd "EVAL (clamacs::wire-port-name (clamacs::editor-wire clamacs::*editor*))")
  (if (and (= *rc* 0) (search "\"127.0.0.1:" *result*))
      (ok "the editor is connected to it at ~A" (string-trim "\"" *result*))
      (fail "the wire's port name is ~A" *result*))
  (cmd "MENU run-lisp STATE")
  (if (string= *result* "disabled")
      (ok "Start clamiga is dimmed once connected")
      (fail "Start clamiga while connected is ~A" *result*))
  ;; The token went through the child's environment: no file of the
  ;; launch is left, and its log is where the editor said.
  (if (and (null (probe-file (concatenate 'string *dir* "clamacs-clamiga.lisp")))
           (null (probe-file (concatenate 'string *dir* "clamacs-clamiga-port"))))
      (ok "the launch left no preamble and no port file behind")
      (fail "the launch's files are still under ~A" *dir*))
  (if (probe-file (concatenate 'string *dir* "clamacs-clamiga.log"))
      (ok "the started clamiga logs to ~Aclamacs-clamiga.log" *dir*)
      (fail "no clamacs-clamiga.log under ~A" *dir*)))

(defun leg-own-lisp ()
  ;; The editor's own Lisp (drive.rexx's phase 5): Talk to the Editor
  ;; Itself switches the wire over -- the REPL window is detached from
  ;; clamiga and attached to the EDITOR's image, loading dev-repl into the
  ;; editor on this first attach, so the wait is long -- and a form at that
  ;; prompt runs in the editor; Talk to clamiga switches back.
  (cmd "MENU clamacs-connect-self STATE")
  (if (string= *result* "enabled")
      (ok "Talk to the Editor Itself is live while talking to clamiga")
      (fail "Talk to the Editor Itself is ~A" *result*))
  (cmd "MENU clamacs-connect-self")
  (let ((echo (wait-echo "REPL attached to the editor itself" 360)))
    (if (string/= echo "")
        (ok "the REPL moved to the editor itself: ~A" echo)
        (progn (cmd "STATUS")
               (fail "the REPL did not attach to the editor itself; the echo area says ~A" *result*))))
  (cmd "EVAL end-of-buffer")
  (let ((p (cursor-line)))
    (cmd "INSERT (room)")
    (cmd "KEY RET")
    ;; ROOM's lines stream in ahead of RESULT and move the cursor with
    ;; them: the form is done only when the cursor sits on the next prompt.
    (let ((y (wait-cursor-past (+ p 2) 120)))
      (when y (setq y (wait-line "CL-USER> " 120)))
      (cmd (format nil "GOTOLINE ~D" (+ p 2)))
      (let ((l (get-line)))
        (if (and y (string/= y "") (search "Heap:" l))
            (ok "(room) at the self REPL reported the editor heap: ~A" l)
            (progn (cmd "STATUS")
                   (fail "(room) at the self REPL gave ~A (cursor ~A); the echo area says ~A" l y *result*)))))
    (cmd "EVAL end-of-buffer"))
  (let ((p (cursor-line)))
    (cmd "INSERT (clamacs:in-editor (clamacs::doc-name (clamacs::editor-active-document clamacs::*editor*)))")
    (cmd "KEY RET")
    (let ((y (wait-cursor-at (+ p 2) 120)))
      (cmd (format nil "GOTOLINE ~D" (+ p 2)))
      (let ((l (get-line)))
        (if (and y (search "*clamacs-repl*" l))
            (ok "IN-EDITOR ran on the editor's task and named the active window: ~A" l)
            (fail "IN-EDITOR gave ~A (cursor ~A)" l y))))
    (cmd "EVAL end-of-buffer"))
  (cmd "MENU clamacs-connect-clamiga")
  (let ((echo (wait-echo "REPL attached to 127.0.0.1:" 120)))
    (if (string/= echo "")
        (ok "Talk to clamiga moved the REPL back: ~A" echo)
        (progn (cmd "STATUS")
               (fail "the REPL did not come back to clamiga; the echo area says ~A" *result*))))
  (cmd "EVAL end-of-buffer"))

(defun quit-editor ()
  "kill-emacs: what the run typed into the fixtures is discarded, no
requester asked.  Then wait for the port to go."
  (cmd "EVAL kill-emacs")
  (ok "asked clamacs to quit")
  (ignore-errors (close *port*))
  (setq *port* nil)
  (if (wait-gone 30)
      (ok "clamacs is gone: its port files are removed and the port refuses")
      (fail "clamacs did not quit within 30 s")))

(defun main ()
  (setq *port* (connect 60))
  (cond ((null *port*)
         (fail "no clamacs port appeared under ~A" *dir*)
         (say "DRIVE-DONE")
         (return-from main nil))
        (t (ok "clamacs port is 127.0.0.1:~A" (file-line (concatenate 'string *dir* "clamacs-port")))))
  (leg-editor-checks)
  (leg-menu)
  (leg-buffers)
  (leg-keys)
  (leg-snapshot)
  (leg-start-clamiga)
  (leg-integration)
  (leg-introspection)
  (leg-repl)
  (leg-debugger)
  (leg-inspector)
  (leg-own-lisp)
  ;; Leave the errors file active, as the Amiga run does.
  (cmd (format nil "OPEN FILE ~A" (fixture "errors.lisp")))
  (pause 25)
  (say "DRIVE-DONE")
  (quit-editor))

(defun second ()
  "The second editor, started by run-drive.sh against the layout file MAIN
wrote: it must come up where the file said, then quit."
  (setq *port* (connect 60))
  (cond ((null *port*)
         (fail "no second editor port appeared under ~A" *dir*)
         (return-from second nil))
        (t (ok "a second editor is at 127.0.0.1:~A" (file-line (concatenate 'string *dir* "clamacs-port")))))
  (let ((got ""))
    (dotimes (i 40)
      (cmd "GETWINDOW")
      (when (and (= *rc* 0) (string/= *result* ""))
        (setq got *result*)
        (return))
      (pause 25))
    (if (string= got *want*)
        (ok "a second editor came up where the file said: ~A" got)
        (fail "the second editor came up at ~A (wanted ~A)" got *want*)))
  (cmd "EVAL save-buffers-kill-emacs")
  (ignore-errors (close *port*))
  (setq *port* nil)
  (if (wait-gone 20)
      (ok "the second editor quit")
      (fail "the second editor did not quit")))

(handler-case
    (cond ((string= *mode* "second") (second))
          (t (main)))
  (error (e)
    (fail "the drive itself failed: ~A" e)))
(finish-output)
(cl-user::quit 0)
